env_args:
  reward_weights:
    stat_0: wins
    weight_0: 20.0
    stat_1: points_gained
    weight_1: 1.0
    stat_2: points_discovered
    weight_2: 10.0
    stat_3: relics_discovered
    weight_3: 10.0
    stat_4: deaths
    weight_4: -1.0
    stat_5: collisions
    weight_5: -0.02
    stat_6: units_moved
    weight_6: 0.01
    stat_7: energy_gained
    weight_7: 0.001
  transform_obs: HybridTransformObs
  transform_action: SimplerActionNoSap
  memory: RelicPointMemory

network:
  model: Pix2Pix_AC
  load_from_checkpoint: None

ppo:
  lr: 1e-4
  num_envs: 8
  num_steps: 1000
  total_timesteps: 1e6
  update_epochs: 4
  num_minibatches: 8
  gamma: 0.99
  gae_lambda: 0.9
  clip_grad_norm: 0.5
  clip_eps: 0.2
  ent_coef: 0.1
  vf_coef: 0.5
  max_grad_norm: 0.5
  anneal_lr: True
  seed: 0
  action_temperature: 2.0