env_args:
  reward_weights:
    stat_0: points_gained
    weight_0: 0.25
    stat_1: points_discovered
    weight_1: 1.0
    stat_2: relics_discovered
    weight_2: 1.0
    stat_3: cells_discovered
    weight_3: 0.01
  transform_obs: HybridTransformObs
  transform_action: SimplerActionNoSap
  memory: RelicPointMemory

network:
  model: Pix2Pix_AC
  load_from_checkpoint: None

ppo:
  # Learning Args
  lr: 1e-4
  num_envs: 16
  num_steps: 256
  total_timesteps: 1e7
  update_epochs: 4
  num_minibatches: 4
  gamma: 0.99
  gae_lambda: 0.95
  clip_grad_norm: 0.5
  clip_eps: 0.2
  ent_coef: 0.1
  vf_coef: 0.5
  max_grad_norm: 0.5
  anneal_lr: True
  action_temperature: 1.0
  match_count_per_episode: 1
  seed: 0

  # Log Args
  use_wandb: True
  arena_freq: 10
  record_freq: 100
  arena_agent: NaiveAgent_Jax
  match_count_per_episode_arena: 1