env_args:
  transform_obs: HybridTransformObs
  transform_action: SimplerActionWithSap
  memory: RelicPointMemory
  reward_phases:
    0:
      type: dense
      weights:
        points_gained: 0.3
        points_discovered: 2.0
        relics_discovered: 1.0
        cells_discovered: 0.01
        energy_gained: 0.0001
    1:
      type: dense
      weights:
        wins: 1.0

network:
  model: Pix2Pix_AC
  load_from_checkpoint: None
  restore_to_cpu: False
  n_resblocks: 5
  n_channels: 128
  embedding_time: 8
  normalize_logits: True
  normalize_value: True

ppo:
  # Learning Args
  lr: 1e-4
  num_envs: 64
  num_steps: 64
  total_timesteps: 6e7
  update_epochs: 4
  num_minibatches: 8
  gamma: 0.9
  gae_lambda: 0.95
  clip_grad_norm: 0.5
  clip_eps: 0.2
  ent_coef: 0.05
  vf_coef: 0.5
  max_grad_norm: 0.5
  anneal_lr: True
  action_temperature: 1.0
  match_count_per_episode: 5
  seed: 1
  selfplay_freq_update: 100

  # Log Args
  verbose: 0
  use_wandb: True
  run_name: purejaxrl_ppo

  # Save Args
  save_checkpoint_path: single_phase
  save_checkpoint_freq: 1000

arena_jax:
  agent: NaiveAgent_Jax
  num_matches: 20
  arena_freq: 500
  record_freq: 500
# arena_std:
#   agent: RelicBoundAgent
#   num_matches: 10
#   arena_freq: 500
#   record_freq: 100