env_args:
  transform_obs: HybridTransformObs
  transform_action: SimplerActionWithSap
  memory: RelicPointMemory

network:
  model: Pix2Pix_AC
  load_from_checkpoint: checkpoints/single_phase_2025_02_09
  restore_to_cpu: True
  n_resblocks: 4
  n_channels: 128
  embedding_time: 8
  normalize_logits: True
  normalize_value: True
